disable_disk_cache: true
destination: /tmp/_site
timezone: Asia/Ho_Chi_Minh

theme: minima
show_excerpts: false
title: Tâm Vũ Trụ
minima:
  skin: dark
header_pages:
  - about.md
disqus:
  shortname: tamvutru
  url: https://tamvutru.org
